(() => {
  'use strict';
  const OWNER='TheWu99', REPO='ChatGPT-Knowledge-Base', API='https://api.github.com';
  // Only these private-repository directories are exposed by the reader.
  // Each immediate child directory is a book; nested Markdown files are chapters.
  const TOKEN_KEY='private-library-token', BOOK_ROOTS=['History/Book','Philosophy/Book'];
  const $=id=>document.getElementById(id);
  const authView=$('authView'), libraryView=$('libraryView'), authForm=$('authForm'), tokenInput=$('tokenInput'), rememberToken=$('rememberToken'), authStatus=$('authStatus'), libraryTree=$('libraryTree'), treeStatus=$('treeStatus'), bookCount=$('bookCount'), content=$('content'), breadcrumb=$('breadcrumb'), loadingState=$('loadingState'), sidebar=$('sidebar');
  let token='', books=[];
  const status=(n,m,t='')=>{n.textContent=m;n.className=`status ${t}`.trim();};
  async function api(path){const r=await fetch(`${API}${path}`,{headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28'},cache:'no-store'});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.message||`GitHub API ${r.status}`);}return r.json();}
  function decode(v){const b=Uint8Array.from(atob(v.replace(/\n/g,'')),c=>c.charCodeAt(0));return new TextDecoder('utf-8').decode(b);}
  async function readFile(path){const p=path.split('/').map(encodeURIComponent).join('/');const d=await api(`/repos/${OWNER}/${REPO}/contents/${p}?t=${Date.now()}`);if(!d.content)throw new Error('无法读取文件内容');return decode(d.content);}
  const esc=v=>String(v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const natural=(a,b)=>String(a).localeCompare(String(b),'zh-CN',{numeric:true,sensitivity:'base'});
  const pretty=s=>decodeURIComponent(s).replace(/[-_]+/g,' ');
  const firstHeading=(md,f)=>{const m=md.match(/^#\s+(.+)$/m);return m?m[1].replace(/[*_`]/g,'').trim():f;};
  const chapterNo=n=>{const m=n.match(/(?:chapter|ch|第)?[-_\s]*(\d{1,3})/i);return m?Number(m[1]):null;};
  const isIntro=n=>/^(readme|overview|introduction|index)\.md$/i.test(n);
  function makeBook(path,collection=''){return{path,collection,title:pretty(path.split('/').pop()),chapters:[],readme:null,overview:null,catalog:null,metadata:null,introPath:null,meta:null,status:'生成中'};}
  function addFile(book,file){const name=file.path.split('/').pop(),dir=file.path.split('/').slice(0,-1).join('/');if(/^readme\.md$/i.test(name)&&dir===book.path)book.readme=file.path;else if(/^(overview|introduction|index)\.md$/i.test(name)&&dir===book.path)book.overview=file.path;else if(/^book\.json$/i.test(name)&&dir===book.path)book.metadata=file.path;else if(/^chapters\.json$/i.test(name)&&dir===book.path)book.catalog=file.path;else if(/\.md$/i.test(name)&&!isIntro(name))book.chapters.push({name,path:file.path,number:chapterNo(name),title:''});}
  async function enrich(book){if(book.metadata){try{book.meta=JSON.parse(await readFile(book.metadata));book.title=book.meta.title||book.meta.bookTitle||book.meta.book_title||book.title;}catch(e){console.warn(e);}}
    if(book.catalog){try{const data=JSON.parse(await readFile(book.catalog)),listed=Array.isArray(data)?data:(Array.isArray(data.chapters)?data.chapters:[]);for(const i of listed){const rel=i.path||i.file||i.filename;if(!rel)continue;const full=rel.startsWith(`${book.path}/`)?rel:`${book.path}/${rel}`;let ch=book.chapters.find(x=>x.path===full);if(!ch){ch={name:rel.split('/').pop(),path:full,number:i.number||i.chapter||chapterNo(rel),title:i.title||''};book.chapters.push(ch);}else{ch.title=i.title||ch.title;ch.number=i.number||i.chapter||ch.number;}}}catch(e){console.warn(e);}}
    const intro=book.readme||book.overview;if(intro){try{const md=await readFile(intro);if(!book.meta?.title)book.title=firstHeading(md,book.title).replace(/^《|》$/g,'');book.introPath=intro;}catch(e){console.warn(e);}}
    book.chapters.sort((a,b)=>a.number!=null&&b.number!=null?a.number-b.number:natural(a.path,b.path));
    const m=book.meta||{},raw=String(m.status||m.state||'').toLowerCase(),total=Number(m.totalChapters||m.total_chapters||m.total||(typeof m.chapters==='number'?m.chapters:0)),done=Number(m.completedChapters||m.completed_chapters||m.completed||book.chapters.length);book.status=/complete|finished|done|已完成/.test(raw)||(total&&done>=total)?'已完成':'生成中';
  }
  async function discoverBooks(){treeStatus.textContent='正在扫描 History 与 Philosophy 的 Book 目录…';const repo=await api(`/repos/${OWNER}/${REPO}`);const tree=await api(`/repos/${OWNER}/${REPO}/git/trees/${encodeURIComponent(repo.default_branch)}?recursive=1&t=${Date.now()}`);const map=new Map();
    for(const root of BOOK_ROOTS){const prefix=`${root}/`,collection=root.split('/')[0],files=tree.tree.filter(x=>x.type==='blob'&&x.path.startsWith(prefix)&&(/\.md$/i.test(x.path)||/(?:book|chapters)\.json$/i.test(x.path)));for(const file of files){const relative=file.path.slice(prefix.length),parts=relative.split('/');if(parts.length<2)continue;const bookPath=`${root}/${parts[0]}`;if(!map.has(bookPath))map.set(bookPath,makeBook(bookPath,collection));addFile(map.get(bookPath),file);}}
    books=[...map.values()].filter(b=>b.metadata||b.catalog||b.readme||b.overview||b.chapters.length);await Promise.all(books.map(enrich));books.sort((a,b)=>a.collection!==b.collection?natural(a.collection,b.collection):natural(a.title,b.title));bookCount.textContent=`${books.length} 本`;treeStatus.textContent=books.length?'':'History/Book 与 Philosophy/Book 中没有发现书籍。';renderTree();
  }
  function renderTree(q=''){q=q.trim().toLowerCase();libraryTree.replaceChildren();let last='';for(const b of books){const mc=b.chapters.filter(c=>`${c.title} ${c.name} ${c.path}`.toLowerCase().includes(q));if(q&&!`${b.title} ${b.path}`.toLowerCase().includes(q)&&!mc.length)continue;if(b.collection&&b.collection!==last){const h=document.createElement('div');h.className='collection-heading';h.textContent=b.collection;libraryTree.appendChild(h);last=b.collection;}
      const g=document.createElement('section');g.className='book-group';if(q)g.classList.add('open');const bb=document.createElement('button');bb.type='button';bb.className='book-row';bb.dataset.path=b.introPath||b.chapters[0]?.path||'';bb.innerHTML=`<span class="caret">›</span><span><span>${esc(b.title)}</span><span class="book-meta">${b.chapters.length} 章</span></span><span class="status-pill">${b.status}</span>`;bb.onclick=async e=>{g.classList.toggle('open');if(bb.dataset.path)await openDoc(bb.dataset.path,b.title,'书籍首页');e.stopPropagation();};const list=document.createElement('div');list.className='chapter-list';for(const c of(q&&!`${b.title} ${b.path}`.toLowerCase().includes(q)?mc:b.chapters)){const bt=document.createElement('button');bt.type='button';bt.className='chapter-row';bt.dataset.path=c.path;const n=c.number!=null?String(c.number).padStart(2,'0'):'•',t=c.title||c.name.replace(/\.md$/i,'').replace(/[-_]+/g,' ');bt.innerHTML=`<span class="chapter-number">${n}</span><span>${esc(t)}</span>`;bt.onclick=async e=>{await openDoc(c.path,b.title,t);e.stopPropagation();};list.appendChild(bt);}g.append(bb,list);libraryTree.appendChild(g);}}
  function inline(t){return esc(t).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>').replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>');}
  function md(markdown){const lines=markdown.replace(/\r/g,'').split('\n');let html='',list='',code=false,buf=[];const close=()=>{if(list){html+=`</${list}>`;list='';}};for(const line of lines){if(/^```/.test(line)){close();if(!code){code=true;buf=[];}else{html+=`<pre><code>${esc(buf.join('\n'))}</code></pre>`;code=false;}continue;}if(code){buf.push(line);continue;}let m=line.match(/^(#{1,6})\s+(.+)$/);if(m){close();html+=`<h${m[1].length}>${inline(m[2])}</h${m[1].length}>`;continue;}if(/^>\s?/.test(line)){close();html+=`<blockquote>${inline(line.replace(/^>\s?/,''))}</blockquote>`;continue;}m=line.match(/^\s*[-*+]\s+(.+)$/);if(m){if(list!=='ul'){close();list='ul';html+='<ul>';}html+=`<li>${inline(m[1])}</li>`;continue;}m=line.match(/^\s*\d+[.)]\s+(.+)$/);if(m){if(list!=='ol'){close();list='ol';html+='<ol>';}html+=`<li>${inline(m[1])}</li>`;continue;}if(/^---+$/.test(line.trim())){close();html+='<hr>';continue;}if(!line.trim()){close();continue;}close();html+=`<p>${inline(line)}</p>`;}close();return html;}
  async function openDoc(path,book,item){loadingState.hidden=false;content.hidden=true;try{content.innerHTML=md(await readFile(path));breadcrumb.textContent=`${book} / ${item}`;document.querySelectorAll('[data-path]').forEach(n=>n.classList.toggle('active',n.dataset.path===path));if(innerWidth<=900)sidebar.classList.remove('open');scrollTo({top:0,behavior:'smooth'});}catch(e){content.innerHTML=`<div class="welcome"><h2>无法读取内容</h2><p>${esc(e.message)}</p></div>`;}finally{loadingState.hidden=true;content.hidden=false;}}
  async function authenticate(v){token=v.trim();if(!token)throw new Error('请输入 GitHub Token');const u=await api('/user');if(u.login!==OWNER)throw new Error(`此阅读器只允许 ${OWNER} 登录`);const r=await api(`/repos/${OWNER}/${REPO}`);if(!r.private)throw new Error('目标知识库不是私人仓库');await discoverBooks();rememberToken.checked?sessionStorage.setItem(TOKEN_KEY,token):sessionStorage.removeItem(TOKEN_KEY);authView.hidden=true;libraryView.hidden=false;}
  authForm.addEventListener('submit',async e=>{e.preventDefault();status(authStatus,'正在验证 GitHub 身份…');$('unlockButton').disabled=true;try{await authenticate(tokenInput.value);status(authStatus,'验证成功','success');}catch(err){token='';status(authStatus,err.message,'error');}finally{$('unlockButton').disabled=false;}});
  $('toggleToken').onclick=()=>{const h=tokenInput.type==='password';tokenInput.type=h?'text':'password';$('toggleToken').textContent=h?'隐藏':'显示';};$('lockButton').onclick=()=>{sessionStorage.removeItem(TOKEN_KEY);token='';books=[];libraryView.hidden=true;authView.hidden=false;tokenInput.value='';};$('refreshButton').onclick=discoverBooks;$('librarySearch').oninput=e=>renderTree(e.target.value);$('sidebarButton').onclick=()=>sidebar.classList.toggle('open');$('fontSize').oninput=e=>document.documentElement.style.setProperty('--reader-font-size',`${e.target.value}px`);$('themeButton').onclick=()=>{const d=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=d?'':'dark';localStorage.setItem('private-library-theme',d?'light':'dark');};if(localStorage.getItem('private-library-theme')==='dark')document.documentElement.dataset.theme='dark';const saved=sessionStorage.getItem(TOKEN_KEY);if(saved){tokenInput.value=saved;rememberToken.checked=true;authenticate(saved).catch(e=>{sessionStorage.removeItem(TOKEN_KEY);status(authStatus,e.message,'error');authView.hidden=false;libraryView.hidden=true;});}
})();
